### ISSUE TITLE
图片路径

### ISSUE THREAD

**Issue by iRuxu** [deepberry/editor#1]
assets/js/img.js中，判断以`/`相对路径开头的，就替换为 `https://cdn.jx3box.com`

- [x] 已完成

**Comment by iRuxu** [comment]
upload组件上传的图，插入的时候，就要将相对路径前面拼装 `https://cdn.jx3box.com` 插进去

- [x] 已完成

**Comment by iRuxu** [comment]
tinymce.vue中，tinymce的上传接口，不能用和cms一样的，需要在cms里新增一个tinymce专用的接口（具体写法参考jx3box-cms对应的），因为它上传的字段和格式是定死的，存在鼠标直接右键粘贴即可上传图片

- [x] 已完成

**Comment by Kaviilee** [comment]
> 

好 `jx3box` !

**Comment by iRuxu** [comment]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/8476969/218139828-c8c56248-7f87-4c3e-a78d-3b9e6bdba7f8.png">

语言问题

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="1851" alt="image" src="https://user-images.githubusercontent.com/8476969/218139964-87246c3d-8962-4687-8b6e-2754bcee18a3.png">

居中

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/8476969/218143649-a0e884c6-f5b9-4c7b-8f57-06ff835f3f69.png">

多个边框

- [x] 已完成
